[warning] tried to patch Rails without Rails being loaded
Loaded suite /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/rake-0.9.2.2/lib/rake/rake_test_loader
Started
FFFFFFFEE............
Finished in 7.562752 seconds.

  1) Failure:
test_should_create_account(AccountsControllerTest) [/home/milo/Work/Web/vibrant/test/functional/accounts_controller_test.rb:30]:
"Account.count" didn't change by 1.
<3> expected but was
<2>.

  2) Failure:
test_should_destroy_account(AccountsControllerTest) [/home/milo/Work/Web/vibrant/test/functional/accounts_controller_test.rb:52]:
"Account.count" didn't change by -1.
<1> expected but was
<2>.

  3) Failure:
test_should_get_edit(AccountsControllerTest) [/home/milo/Work/Web/vibrant/test/functional/accounts_controller_test.rb:43]:
Expected response to be a <:success>, but was <302>

  4) Failure:
test_should_get_index(AccountsControllerTest) [/home/milo/Work/Web/vibrant/test/functional/accounts_controller_test.rb:17]:
Expected response to be a <:success>, but was <302>

  5) Failure:
test_should_get_new(AccountsControllerTest) [/home/milo/Work/Web/vibrant/test/functional/accounts_controller_test.rb:23]:
Expected response to be a <:success>, but was <302>

  6) Failure:
test_should_show_account(AccountsControllerTest) [/home/milo/Work/Web/vibrant/test/functional/accounts_controller_test.rb:38]:
Expected response to be a <:success>, but was <302>

  7) Failure:
test_should_update_account(AccountsControllerTest) [/home/milo/Work/Web/vibrant/test/functional/accounts_controller_test.rb:48]:
Expected response to be a redirect to <http://test.host/accounts/507d679935d3102432000020> but was a redirect to <http://test.host/>

  8) Error:
test_should_get_error_404(ErrorsControllerTest):
ActionController::RoutingError: No route matches {:controller=>"errors", :action=>"error_404"}
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:465:in `raise_routing_error'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:461:in `rescue in generate'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:453:in `generate'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:494:in `generate'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:490:in `generate_extras'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:486:in `extra_keys'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_controller/test_case.rb:145:in `assign_parameters'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_controller/test_case.rb:438:in `process'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_controller/test_case.rb:49:in `process'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/devise-1.5.3/lib/devise/test_helpers.rb:19:in `block in process'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/devise-1.5.3/lib/devise/test_helpers.rb:70:in `catch'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/devise-1.5.3/lib/devise/test_helpers.rb:70:in `_catch_warden'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/devise-1.5.3/lib/devise/test_helpers.rb:19:in `process'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_controller/test_case.rb:365:in `get'
    /home/milo/Work/Web/vibrant/test/functional/errors_controller_test.rb:5:in `block in <class:ErrorsControllerTest>'

  9) Error:
test_should_get_error_500(ErrorsControllerTest):
ActionController::RoutingError: No route matches {:controller=>"errors", :action=>"error_500"}
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:465:in `raise_routing_error'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:461:in `rescue in generate'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:453:in `generate'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:494:in `generate'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:490:in `generate_extras'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_dispatch/routing/route_set.rb:486:in `extra_keys'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_controller/test_case.rb:145:in `assign_parameters'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_controller/test_case.rb:438:in `process'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_controller/test_case.rb:49:in `process'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/devise-1.5.3/lib/devise/test_helpers.rb:19:in `block in process'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/devise-1.5.3/lib/devise/test_helpers.rb:70:in `catch'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/devise-1.5.3/lib/devise/test_helpers.rb:70:in `_catch_warden'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/devise-1.5.3/lib/devise/test_helpers.rb:19:in `process'
    /usr/local/rvm/gems/ruby-1.9.2-head@oboe/gems/actionpack-3.1.3/lib/action_controller/test_case.rb:365:in `get'
    /home/milo/Work/Web/vibrant/test/functional/errors_controller_test.rb:10:in `block in <class:ErrorsControllerTest>'

21 tests, 25 assertions, 7 failures, 2 errors, 0 skips

Test run options: --seed 62018
Errors running test:units, test:functionals!
